[package]
name = "job"
version = "0.1.0"
edition = "2021"

[dependencies]
cron = "0.12.0"
async-trait = "0.1.83"
anyhow = "1.0.94"
tokio = { version = "1.42.0", features = ["full"] }

[[examples]]
name = "examples"

