name: job-manager
services:
  cassandra:
    image: cassandra:latest
    container_name: cassandra-job
    ports:
      - "9042:9042"
    environment:
      - CASSANDRA_USER=cassandra
      - CASSANDRA_PASSWORD=cassandra
    volumes:
      - cassandra-data:/var/lib/cassandra
    healthcheck:
      test: [ "CMD", "cqlsh", "-e", "describe keyspaces" ]
      interval: 30s
      timeout: 10s
      retries: 5
  manager:
    image: job:latest
    container_name: job
    environment:
      - API_KEY=${API_KEY}
    depends_on:
      cassandra:
        condition: service_healthy

volumes:
  data:
    driver: local
  cassandra-data: