[package]
name = "job"
version = "0.1.0"
edition = "2021"

[dependencies]
job-core = { path = "../crates/job-core" }
tokio = { version = "1.42.0", features = ["full"] }
reqwest = { version = "0.11", features = ["json"] }
