[package]
name = "job-core"
version = "0.1.0"
edition = "2021"

[dependencies]
async-trait = "0.1.83"
anyhow = "1.0.94"
chrono = "0.4.37"
cassandra-cpp = "3.0.2"
cron = { version = "0.12.0"}
serde = { version = "1.0", features = ["derive"] }
hostname = "0.3"
gethostname = "0.3"
log = "0.4.25"
derive_more = "0.99"
tokio = { version = "1.42.0", features = ["full"] }
reqwest = { version = "0.11", features = ["json"] }
